import express from 'express';
const router = express.Router();

import authRoutes from './auth.routes.js';
import uploadRoutes from './upload.routes.js';
import adminRoutes from './admin.routes.js';
import siteRoutes from './site.routes.js';
import teamRoutes from './team.routes.js';
import userCategoryRoutes from './userCategory.routes.js';
import callRoutes from './call.routes.js';
import followupRoutes from './followup.routes.js';
import leadRoutes from './lead.routes.js';
import colonyMapRoutes from './colonyMap.routes.js';
import plotBookingRoutes from './plotBooking.routes.js';
import paymentRoutes from './payment.routes.js';
import clientRoutes from './client.routes.js';
import clientActivityRoutes from './clientActivity.routes.js';
import dashboardRoutes from './dashboard.routes.js';
import contentShareRoutes from './contentShare.routes.js';
import attendanceRoutes from './attendance.routes.js';
import chatRoutes from './chat.routes.js';
import financialSettingsRoutes from './financialSettings.routes.js';
import contactRoutes from './contact.routes.js';
import directionsRoutes from './directions.routes.js';

router.use('/auth', authRoutes);
router.use('/upload', uploadRoutes);
router.use('/admin', adminRoutes);
router.use('/site', siteRoutes);
router.use('/teams', teamRoutes);
router.use('/site/user-categories', userCategoryRoutes);
router.use('/calls', callRoutes);
router.use('/followups', followupRoutes);
router.use('/leads', leadRoutes);
router.use('/colony-maps', colonyMapRoutes);
router.use('/bookings', plotBookingRoutes);
router.use('/payments', paymentRoutes);
router.use('/clients', clientRoutes);
router.use('/activities', clientActivityRoutes);
router.use('/dashboard', dashboardRoutes);
router.use('/content-share', contentShareRoutes);
router.use('/attendance', attendanceRoutes);
router.use('/chat', chatRoutes);
router.use('/financial-settings', financialSettingsRoutes);
router.use('/contacts', contactRoutes);
router.use('/directions', directionsRoutes);

export default router;
