-- Add NOT_INTERESTED to leads status check constraint
ALTER TABLE IF EXISTS leads DROP CONSTRAINT IF EXISTS leads_status_check;
ALTER TABLE IF EXISTS leads
ADD CONSTRAINT leads_status_check
CHECK (status IN (
  'NEW', 'CONTACTED', 'INTERESTED', 'NOT_INTERESTED',
  'SITE_VISIT', 'NEGOTIATION', 'BOOKED', 'LOST',
  'INCOMING_OFF', 'SWITCH_OFF', 'NOT_ANSWERING'
));
